name: SITL Tests (Code Coverage)

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-simulation-bionic:2020-01-29
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Download MAVSDK
      run: wget https://github.com/mavlink/MAVSDK/releases/download/v0.24.0/mavsdk_0.24.0_ubuntu18.04_amd64.deb
    - name: Install MAVSDK
      run: dpkg -i mavsdk_0.24.0_ubuntu18.04_amd64.deb
    - name: Build PX4 in SITL integration test mode
      run: DONT_RUN=1 make px4_sitl gazebo mavsdk_tests
    - name: Run Coverage Tests
      run: make tests_integration_coverage
    # We are not actively using coveralls, but we keep the config
    # in case the service should be re-enabled later
    # - name: Upload coverage information to Coveralls
    #   uses: coverallsapp/github-action@master
    #   with:
    #     path-to-lcov: coverage/lcov.info
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload coverage information to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: mavsdk
        file: coverage/lcov.info
